version: '2'

services:
 test-service:
    build:
      context: ./cds-service-example-nodejs
      dockerfile: Dockerfile
    image: cdshooks/test-service
    networks:
     - internal
  invoker:
    build:
      context: ./cds-invoker
      dockerfile: Dockerfile
    image: cdshooks/cds-invoker
    networks:
     - internal

networks:
  internal:
    driver: bridge
