version: '2'

services:
  test-service:
    build:
      context: ./cds-service-example-nodejs
      dockerfile: Dockerfile
    image: cdshooks/test-service
    expose:
      - 9000
    environment:
      PORT: "9000"
    networks:
     - internal
  invoker:
    build:
      context: ./cds-invoker
      dockerfile: Dockerfile
    image: cdshooks/cds-invoker
    expose:
      - 9000
    environment:
      PORT: "9000"
    networks:
     - internal

networks:
  internal:
    driver: bridge
