version: '2'

services:
  test-service:
    networks:
     - proxy-tier
    environment:
     - BASE_URL=https://test-service.cds-hooks.org
     - VIRTUAL_HOST=test-service.cds-hooks.org
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=9000
     - LETSENCRYPT_HOST=test-service.cds-hooks.org
     - LETSENCRYPT_EMAIL=letsencrypt@mg.syncfor.science
  invoker:
    networks:
     - proxy-tier
    environment:
     - BASE_URL=https://invoker.cds-hooks.org
     - VIRTUAL_HOST=invoker.cds-hooks.org
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=3000
     - LETSENCRYPT_HOST=invoker.cds-hooks.org
     - LETSENCRYPT_EMAIL=letsencrypt@mg.syncfor.science
networks:
  proxy-tier:
    external:
      name: nginx-proxy

volumes:
  derby: {}
